
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}  # Reference from .env file
      NODE_ENV: ${NODE_ENV}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      custom_network:

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      custom_network:
        ipv4_address: 192.168.1.100  # Fixed IP address

volumes:
  postgres_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
